#!/bin/bash
GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-mingw32-g++ go build -ldflags "-w -s"
#CC=x86_64-w64-mingw32-gcc CXX=x86_64-mingw32-g++ fyne package --os windows --icon Icon.png